name: Run Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Replace 3.x with your desired Python version

      # Step 3: Install pytest
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Step 4: Run pytest
      - name: Run tests
        run: pytest
